# Generated by Django 6.0.6 on 2026-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('fish', models.CharField(max_length=80)),
                ('message', models.TextField(max_length=200)),
                ('recommend', models.CharField(max_length=3)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
