# Generated by Django 6.0.6 on 2026-07-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
